### ISSUE TITLE
RedstoneBot down - 2021/06/11

### ISSUE THREAD

**Issue by carljen** [ChromeUniverse/RedstoneBot#2]
![image](https://user-images.githubusercontent.com/85750819/121701965-063e8380-cb04-11eb-885f-eb2f114caca8.png)
![image](https://user-images.githubusercontent.com/85750819/121702000-0fc7eb80-cb04-11eb-8ba2-47d1387d7dad.png)

I gave the correct permission needed and double checked if the ip address was correct but the Redstonebot still says incorrect ip. 
My server is smpeep.ploudos.me 

thank you

**Comment by ChromeUniverse** [comment]
Hi, @carljen! Thanks for bringing this to my attention. 

To be honest, I'm not sure what's going on exactly. It seems that RedstoneBot has stopped working entirely. Commands like `status` and `start` aren't working either:

![image](https://user-images.githubusercontent.com/33258966/121710265-d1084600-caaf-11eb-9dc4-74e6a14f0228.png)

I haven't used PloudOS in quite some time, but it appears that the website's layout has changed. Since RedstoneBot is essentially a webscraper, minor changes in the site's HTML and internal API response data can easily break the bot.

RedstoneBot has had issues ever since it was created (including database state update, error handling, and networking problems). I'll try to find time to fix some of these bugs and iron out some other kinks in the coming weeks.

I'll keep this issue open while I work on fixing RedstoneBot, so feel free to share other bugs as well. Stay tuned for possible updates.

**Comment by carljen** [comment]
thanks you so much!

**Comment by ChromeUniverse** [comment]
Turns out all RedstoneBot (probably) needed was a restart. 🤪 Apparently, it just logged out from Ploudos and needed to log back in again. After the restart, I'm able to run commands like `status`, `start`, `stop`, `reset`, and `setup` as usual.

![image](https://user-images.githubusercontent.com/33258966/121762550-fd9e7b00-cb0c-11eb-92d0-2243f015d431.png)

Could you try running the `setup` command once again, @carljen? Let me know if it's working for you now.

**Comment by ChromeUniverse** [comment]
I still plan on working on bug fixes soon, but for now, it seems that everything is working just fine.

**Comment by carljen** [comment]
Tried it and it works, thank you so much!!!!!!!

**Comment by ChromeUniverse** [comment]
@carljen Glad to hear it! 😄

**Comment by ChromeUniverse** [comment]
I'll be closing this issue for now. If you find any other bugs, feel free to open a new one and report them. Thanks again, cheers!
